import {test,expect} from '@playwright/test';
test('onboarding, comando, isolamento, memórias e navegação',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'Sua live, bem acompanhada.'})).toBeVisible();
 await page.screenshot({path:'artifacts/dashboard-dark.png',fullPage:true});
 await page.getByRole('button',{name:'Criar primeiro bot',exact:true}).click();
 await page.getByLabel('Nome do perfil',{exact:true}).fill('Canal Cactus');
 await page.getByLabel('Nome do canal',{exact:true}).fill('cactus');
 await page.getByRole('button',{name:'Salvar perfil',exact:true}).click();
 await expect(page.getByText('Perfil salvo.',{exact:true})).toBeVisible();
 await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Comandos',exact:true}).click();
 await page.getByRole('button',{name:'Novo comando',exact:true}).click();
 await page.getByLabel('Nome',{exact:true}).fill('Saudação');
 await page.getByLabel('Comando',{exact:true}).fill('!ola');
 await page.getByRole('textbox',{name:'Resposta',exact:true}).fill('Olá, $user. Bem-vindo à comunidade!');
 await page.getByRole('button',{name:'Salvar comando',exact:true}).click();
 await expect(page.getByRole('cell',{name:'!ola Saudação'})).toBeVisible();
 await page.getByRole('button',{name:'Automações',exact:true}).click();
 await page.getByRole('button',{name:'Editar Saudação'}).click();
 await expect(page.locator('.react-flow__node')).toHaveCount(2);
 await page.screenshot({path:'artifacts/flow-editor.png',fullPage:true});
 await page.getByRole('button',{name:'Salvar fluxo',exact:true}).click();
 await page.getByRole('button',{name:'Memórias',exact:true}).click();
 await page.getByRole('button',{name:'Nova memória',exact:true}).click();
 await page.getByLabel('Caminho da nota').fill('usuarios/ana.md');
 await page.getByLabel('Conteúdo Markdown').fill('---\ntags: [xadrez]\n---\n# Ana\nGosta de xadrez.');
 await page.getByRole('button',{name:'Salvar',exact:true}).click();
 await expect(page.getByText('Memória salva.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Perfis de bot',exact:true}).click();
 await page.getByRole('button',{name:'Novo perfil',exact:true}).click();
 await page.getByLabel('Nome do perfil',{exact:true}).fill('Segundo canal');
 await page.getByRole('button',{name:'Salvar perfil',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Comandos',exact:true}).click();
 await expect(page.getByText('Sua primeira conversa começa aqui')).toBeVisible();
 await page.getByRole('button',{name:'Memórias',exact:true}).click();
 await expect(page.getByRole('button',{name:/ana.md/})).toHaveCount(0);
 for(const label of ['Inteligência artificial','Comunidade','Biblioteca de presets','Histórico','Estatísticas','Configurações']){await page.getByRole('button',{name:label,exact:true}).click();await expect(page.getByRole('heading',{name:label,exact:true})).toBeVisible()}
 await page.getByRole('button',{name:'Visão geral',exact:true}).click();
 await page.getByRole('button',{name:'Alternar tema'}).click();
 await page.screenshot({path:'artifacts/dashboard-light.png',fullPage:true});
 await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','light');
 expect(errors).toEqual([]);
});
test('janela pequena não produz rolagem horizontal',async({page})=>{
 await page.setViewportSize({width:720,height:800});await page.goto('/');
 await expect(page.getByRole('heading',{name:'Sua live, bem acompanhada.'})).toBeVisible();
 const dimensions=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));
 expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.width);
 await page.screenshot({path:'artifacts/dashboard-small.png',fullPage:true});
});

test('cor personalizada persiste e restauração segue o tema',async({page})=>{
 await page.goto('/');
 await page.getByRole('button',{name:'Configurações',exact:true}).click();
 await page.getByLabel('Cor de destaque',{exact:true}).fill('#224488');
 await expect(page.locator('html')).toHaveCSS('--accent','#224488');
 await page.reload();
 await expect(page.locator('html')).toHaveCSS('--accent','#224488');
 await page.getByRole('button',{name:'Configurações',exact:true}).click();
 await page.getByRole('button',{name:'Restaurar padrão'}).click();
 await expect(page.locator('html')).toHaveCSS('--accent','#b7ef72');
});

test('catálogo de variáveis insere marcador e informa limite da prévia web',async({page})=>{
 await page.goto('/');
 await page.getByRole('button',{name:'Criar primeiro bot',exact:true}).click();
 await page.getByLabel('Nome do perfil',{exact:true}).fill('Variáveis');
 await page.getByRole('button',{name:'Salvar perfil',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Comandos',exact:true}).click();
 await page.getByRole('button',{name:'Novo comando',exact:true}).click();
 const response=page.getByRole('textbox',{name:'Resposta',exact:true});
 await response.fill('Olá, convidado!');await response.press('Home');
 for(let i=0;i<5;i++)await response.press('ArrowRight');
 for(let i=0;i<9;i++)await response.press('Shift+ArrowRight');
 await page.getByRole('button',{name:'+ Nome da pessoa',exact:true}).click();
 await expect(response).toHaveValue('Olá, {{user}}!');
 await expect(page.locator('.message-readable')).toContainText('Nome da pessoa');
 await page.screenshot({path:'artifacts/variables-message.png',fullPage:true});
 await response.fill('Olá, ');
 await page.getByText('Inserir variável e testar mensagem',{exact:true}).click();
 await page.getByRole('combobox',{name:'Categoria',exact:true}).selectOption('Mensagem');
 await page.getByLabel('Buscar informação',{exact:true}).fill('primeira');
 await page.locator('.variable-catalog button').click();
 await page.getByLabel('Se não houver valor, mostrar',{exact:true}).fill('amigo');
 await page.getByRole('combobox',{name:'Como mostrar',exact:true}).selectOption('upper');
 await page.getByRole('button',{name:'Inserir na mensagem',exact:true}).click();
 await expect(response).toHaveValue('Olá, {{arg0|default:amigo|upper}}');
 await page.getByText('Testar como a mensagem vai ficar',{exact:true}).click();
 await expect(page.getByRole('button',{name:'Conferir variáveis',exact:true})).toBeDisabled();
 await page.screenshot({path:'artifacts/variables-catalog.png',fullPage:true});
 await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Variáveis',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Variáveis do perfil'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Salvar variável',exact:true})).toBeDisabled();
 await page.setViewportSize({width:720,height:800});
 const size=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));expect(size.scroll).toBeLessThanOrEqual(size.width);
});
