import {test,expect} from '@playwright/test';
test('painel TXT e sons permite configurar regras e espectadores com limites claros',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Criar primeiro bot',exact:true}).click();
 await page.getByLabel('Nome do perfil',{exact:true}).fill('Arquivos e sons');await page.getByRole('button',{name:'Salvar perfil',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Respostas e sons',exact:true}).click();
 await page.getByRole('button',{name:'Adicionar resposta TXT',exact:true}).click();await page.getByLabel('Palavra ou expressão',{exact:true}).fill('café');
 await page.getByRole('combobox',{name:'Escolher resposta',exact:true}).selectOption('sequence');await expect(page.getByRole('button',{name:'Vincular TXT',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Adicionar pessoa',exact:true}).click();await page.getByLabel('Nome no chat',{exact:true}).fill('ana');await page.getByLabel('Apelido',{exact:true}).fill('Aninha');
 await page.getByRole('combobox',{name:'Quando tocar',exact:true}).selectOption('interval');await page.getByRole('switch',{name:'Ativar sons por espectador',exact:true}).click();
 await page.getByRole('combobox',{name:'Disparar som',exact:true}).selectOption('join');await page.getByRole('switch',{name:'Monitorar entradas silenciosas na Twitch',exact:true}).click();await expect(page.getByRole('combobox',{name:'Dispositivo de saída dos sons',exact:true})).toBeVisible();
 await expect(page.getByRole('switch',{name:'Ativar sons por espectador',exact:true})).toHaveAttribute('aria-checked','true');
 await expect(page.getByRole('button',{name:'Salvar respostas e sons',exact:true})).toBeDisabled();
 await page.screenshot({path:'artifacts/txt-and-viewer-sounds.png',fullPage:true});
 await page.getByRole('button',{name:'Recolher todos',exact:true}).first().click();await expect(page.getByLabel('Palavra ou expressão',{exact:true})).toHaveCount(1);await expect(page.locator('.item-toggle').first()).toHaveAttribute('aria-expanded','false');await expect(page.locator('.item-body').first()).toHaveAttribute('inert');await expect.poll(async()=>page.locator('.item').first().evaluate(el=>el.offsetHeight)).toBeLessThan(120);
 await page.getByRole('button',{name:'Expandir todos',exact:true}).first().click();await expect(page.locator('.item-toggle').first()).toHaveAttribute('aria-expanded','true');await expect(page.locator('.item-body').first()).not.toHaveAttribute('inert');await expect(page.getByLabel('Palavra ou expressão',{exact:true})).toBeVisible();await expect.poll(async()=>page.locator('.item').first().evaluate(el=>el.offsetHeight)).toBeGreaterThan(300);
 await page.getByRole('button',{name:'Remover pessoa',exact:true}).click();await expect(page.getByLabel('Nome no chat',{exact:true})).toHaveCount(0);
});
test('resenha com IA cria geração antes do envio e variável por nome',async({page})=>{
 await page.goto('/');
 await page.getByRole('button',{name:'Criar primeiro bot',exact:true}).click();
 await page.getByLabel('Nome do perfil',{exact:true}).fill('Resenha');
 await page.getByRole('button',{name:'Salvar perfil',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Comandos',exact:true}).click();
 await page.getByRole('button',{name:'Resenha com IA',exact:true}).click();
 await page.getByText('Testar resposta contextual',{exact:true}).click();
 await expect(page.getByRole('textbox',{name:'Mensagem da pessoa',exact:true})).toHaveValue('O Thenees hoje está amassando na play');
 await expect(page.getByRole('button',{name:'Gerar resposta de teste',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Salvar resenha do chat',exact:true}).click();
 await page.getByRole('button',{name:'Editar Resenha do chat',exact:true}).click();
 await expect(page.locator('.react-flow__node')).toHaveCount(3);
 await page.locator('.react-flow__node').filter({hasText:'Gerar resposta da IA (variável)'}).click();
 await expect(page.getByLabel('Nome da resposta',{exact:true})).toHaveValue('aiResponse');
 await page.locator('.react-flow__node').filter({hasText:'Enviar mensagem'}).click();
 await expect(page.getByRole('textbox',{name:'Mensagem / conteúdo',exact:true})).toHaveValue('{{local.aiResponse}}');
 await expect(page.locator('.message-readable')).toContainText('Resposta da IA');
 await page.screenshot({path:'artifacts/ai-contextual-flow.png',fullPage:true});
});
test('onboarding, comando, isolamento, memórias e navegação',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'Sua live, bem acompanhada.'})).toBeVisible();
 await page.screenshot({path:'artifacts/dashboard-dark.png',fullPage:true});
 await page.getByRole('button',{name:'Criar primeiro bot',exact:true}).click();
 await page.getByLabel('Nome do perfil',{exact:true}).fill('Canal Cactus');
 await page.getByLabel('Nome do canal',{exact:true}).fill('cactus');
 await page.getByRole('button',{name:'Salvar perfil',exact:true}).click();
 await expect(page.getByText('Perfil salvo.',{exact:true})).toBeVisible();
 await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Comandos',exact:true}).click();
 await page.getByRole('button',{name:'Novo comando',exact:true}).click();
 await page.getByLabel('Nome',{exact:true}).fill('Saudação');
 await page.getByLabel('Comando',{exact:true}).fill('!ola');
 await page.getByRole('textbox',{name:'Resposta',exact:true}).fill('Olá, $user. Bem-vindo à comunidade!');
 await page.getByRole('button',{name:'Salvar comando',exact:true}).click();
 await expect(page.getByRole('cell',{name:'!ola Saudação'})).toBeVisible();
 await page.getByRole('button',{name:'Automações',exact:true}).click();
 await page.getByRole('button',{name:'Editar Saudação'}).click();
 await expect(page.locator('.react-flow__node')).toHaveCount(2);
 await page.screenshot({path:'artifacts/flow-editor.png',fullPage:true});
 await page.getByRole('button',{name:'Salvar fluxo',exact:true}).click();
 await page.getByRole('button',{name:'Memórias',exact:true}).click();
 await page.getByRole('button',{name:'Nova memória',exact:true}).click();
 await page.getByLabel('Caminho da nota').fill('usuarios/ana.md');
 await page.getByLabel('Conteúdo Markdown').fill('---\ntags: [xadrez]\n---\n# Ana\nGosta de xadrez.');
 await page.getByRole('button',{name:'Salvar',exact:true}).click();
 await expect(page.getByText('Memória salva.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Perfis de bot',exact:true}).click();
 await page.getByRole('button',{name:'Novo perfil',exact:true}).click();
 await page.getByLabel('Nome do perfil',{exact:true}).fill('Segundo canal');
 await page.getByRole('button',{name:'Salvar perfil',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Comandos',exact:true}).click();
 await expect(page.getByText('Sua primeira conversa começa aqui')).toBeVisible();
 await page.getByRole('button',{name:'Memórias',exact:true}).click();
 await expect(page.getByRole('button',{name:/ana.md/})).toHaveCount(0);
 for(const label of ['Inteligência artificial','Comunidade','Discord','Biblioteca de presets','Histórico','Estatísticas','Configurações']){await page.locator('.sidebar').getByRole('button',{name:label,exact:true}).click();await expect(page.getByRole('heading',{name:label,exact:true})).toBeVisible()}
 await page.getByRole('button',{name:'Visão geral',exact:true}).click();
 await page.getByRole('button',{name:'Alternar tema'}).click();
 await page.screenshot({path:'artifacts/dashboard-light.png',fullPage:true});
 await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','light');
 expect(errors).toEqual([]);
});
test('janela pequena não produz rolagem horizontal',async({page})=>{
 await page.setViewportSize({width:720,height:800});await page.goto('/');
 await expect(page.getByRole('heading',{name:'Sua live, bem acompanhada.'})).toBeVisible();
 const dimensions=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));
 expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.width);
 await page.screenshot({path:'artifacts/dashboard-small.png',fullPage:true});
});

test('cor personalizada persiste e restauração segue o tema',async({page})=>{
 await page.goto('/');
 await page.getByRole('button',{name:'Configurações',exact:true}).click();
 await page.getByLabel('Cor de destaque',{exact:true}).fill('#224488');
 await expect(page.locator('html')).toHaveCSS('--accent','#224488');
 await page.reload();
 await expect(page.locator('html')).toHaveCSS('--accent','#224488');
 await page.getByRole('button',{name:'Configurações',exact:true}).click();
 await page.getByRole('button',{name:'Restaurar padrão'}).click();
 await expect(page.locator('html')).toHaveCSS('--accent','#b7ef72');
});

test('catálogo de variáveis insere marcador e informa limite da prévia web',async({page})=>{
 await page.goto('/');
 await page.getByRole('button',{name:'Criar primeiro bot',exact:true}).click();
 await page.getByLabel('Nome do perfil',{exact:true}).fill('Variáveis');
 await page.getByRole('button',{name:'Salvar perfil',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Comandos',exact:true}).click();
 await page.getByRole('button',{name:'Novo comando',exact:true}).click();
 const response=page.getByRole('textbox',{name:'Resposta',exact:true});
 await response.fill('Olá, convidado!');await response.press('Home');
 for(let i=0;i<5;i++)await response.press('ArrowRight');
 for(let i=0;i<9;i++)await response.press('Shift+ArrowRight');
 await page.getByRole('button',{name:'+ Nome da pessoa',exact:true}).click();
 await expect(response).toHaveValue('Olá, {{user}}!');
 await expect(page.locator('.message-readable')).toContainText('Nome da pessoa');
 await page.screenshot({path:'artifacts/variables-message.png',fullPage:true});
 await response.fill('Olá, ');
 await page.getByText('Inserir variável e testar mensagem',{exact:true}).click();
 await page.getByRole('combobox',{name:'Categoria',exact:true}).selectOption('Mensagem');
 await page.getByLabel('Buscar informação',{exact:true}).fill('primeira');
 await page.locator('.variable-catalog button').click();
 await page.getByLabel('Se não houver valor, mostrar',{exact:true}).fill('amigo');
 await page.getByRole('combobox',{name:'Como mostrar',exact:true}).selectOption('upper');
 await page.getByRole('button',{name:'Inserir na mensagem',exact:true}).click();
 await expect(response).toHaveValue('Olá, {{arg0|default:amigo|upper}}');
 await page.getByText('Testar como a mensagem vai ficar',{exact:true}).click();
 await expect(page.getByRole('button',{name:'Conferir variáveis',exact:true})).toBeDisabled();
 await page.screenshot({path:'artifacts/variables-catalog.png',fullPage:true});
 await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Variáveis',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Variáveis do perfil'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Salvar variável',exact:true})).toBeDisabled();
 await page.setViewportSize({width:720,height:800});
 const size=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));expect(size.scroll).toBeLessThanOrEqual(size.width);
});
