import {useEffect,useState} from 'react';
import {open} from '@tauri-apps/plugin-dialog';
import {api,desktop,errorText} from './api';
import {Card,Field,Toggle} from './components';
import {playViewerSound} from './viewerSound';
type Asset={id:string;kind:string;name:string};
type Reply={id:string;enabled:boolean;keyword:string;matching:string;selection:string;asset:string;cooldown:number;userCooldown:number};
type Person={id:string;enabled:boolean;name:string;nickname:string;userId:string;asset:string;mode:string;cooldown:number;volume:number};
type Config={repliesEnabled:boolean;soundsEnabled:boolean;replies:Reply[];people:Person[]};
const blank:Config={repliesEnabled:false,soundsEnabled:false,replies:[],people:[]};
export default function ChatExtras({profileId}:{profileId:string}){
 const [config,setConfig]=useState<Config>(blank);const [assets,setAssets]=useState<Asset[]>([]);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [loaded,setLoaded]=useState(!desktop);
 const [preview,setPreview]=useState<{count:number;lines:string[]}|null>(null);
 useEffect(()=>{let live=true;if(desktop)api<{config:Config;assets:Asset[]}>('chatExtras.get',{profileId}).then(v=>{if(live){setConfig(v.config);setAssets(v.assets);setLoaded(true)}}).catch(e=>{if(live)setError(errorText(e))});return()=>{live=false}},[profileId]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function choose(kind:string,update:(asset:string)=>void){await run(async()=>{
  const path=await open({multiple:false,filters:[{name:kind==='txt'?'Respostas UTF-8':'Áudio',extensions:kind==='txt'?['txt']:['wav','mp3','ogg']}]});if(typeof path!=='string')return;
  const asset=await api<Asset>('chatExtras.import',{profileId,kind,path});setAssets(a=>a.concat(asset));update(asset.id);
 })}
 const reply=(id:string,patch:Partial<Reply>)=>setConfig(c=>({...c,replies:c.replies.map(r=>r.id===id?{...r,...patch}:r)}));
 const person=(id:string,patch:Partial<Person>)=>setConfig(c=>({...c,people:c.people.map(r=>r.id===id?{...r,...patch}:r)}));
 const file=(kind:string,value:string,change:(id:string)=>void)=><div className="row"><select aria-label={kind==='txt'?'Arquivo de respostas':'Arquivo de som'} value={value} onChange={e=>change(e.target.value)}><option value="">Escolha um arquivo</option>{assets.filter(a=>a.kind===kind).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><button disabled={!desktop||busy} onClick={()=>void choose(kind,change)}>{kind==='txt'?'Vincular TXT':'Escolher som'}</button></div>;
 return <div className="form-pad"><p>Respostas prontas para palavras do chat e uma trilha de chegada para cada pessoa. As alterações entram em vigor ao clicar em Salvar respostas e sons.</p>{!desktop&&<p className="notice">Prévia da configuração. Arquivos, reprodução e salvamento estão disponíveis no aplicativo desktop.</p>}
 <fieldset disabled={busy||!loaded} style={{border:0,padding:0,minWidth:0}}>
 <Card title="Respostas por arquivo TXT"><Toggle label="Ativar respostas TXT" checked={config.repliesEnabled} onChange={repliesEnabled=>setConfig({...config,repliesEnabled})}/><p className="help">Uma resposta por linha, até 450 caracteres. Linhas vazias são ignoradas. Use UTF-8. Alterações no arquivo original valem no próximo disparo. A primeira regra disponível responde; outras automações não executam nessa mensagem.</p>
 {config.replies.map((r,i)=><section key={r.id} className="card"><div className="row between"><strong>Regra {i+1}</strong><Toggle label={'Ativar regra '+(i+1)} checked={r.enabled} onChange={enabled=>reply(r.id,{enabled})}/></div>
 <Field label="Palavra ou expressão"><input value={r.keyword} maxLength={100} onChange={e=>reply(r.id,{keyword:e.target.value})}/></Field>
 <div className="form-grid"><Field label="Reconhecer"><select value={r.matching} onChange={e=>reply(r.id,{matching:e.target.value})}><option value="word">Palavra / expressão inteira</option><option value="contains">Qualquer trecho da mensagem</option></select></Field><Field label="Escolher resposta"><select value={r.selection} onChange={e=>reply(r.id,{selection:e.target.value})}><option value="random">Aleatória, sem repetir a última</option><option value="sequence">Em sequência</option></select></Field></div>
 {file('txt',r.asset,asset=>reply(r.id,{asset}))}<div className="form-grid"><Field label="Intervalo da regra (segundos)"><input type="number" min="1" max="86400" value={r.cooldown} onChange={e=>reply(r.id,{cooldown:+e.target.value})}/></Field><Field label="Intervalo por pessoa (segundos)"><input type="number" min="0" max="86400" value={r.userCooldown} onChange={e=>reply(r.id,{userCooldown:+e.target.value})}/></Field></div>
 <button disabled={!desktop||!r.asset} onClick={()=>void run(async()=>{setPreview(await api('chatExtras.preview',{profileId,asset:r.asset}))})}>Conferir linhas</button><button className="danger" onClick={()=>setConfig({...config,replies:config.replies.filter(x=>x.id!==r.id)})}>Remover regra</button></section>)}
 <button onClick={()=>setConfig({...config,replies:config.replies.concat({id:crypto.randomUUID(),enabled:true,keyword:'',matching:'word',selection:'random',asset:'',cooldown:30,userCooldown:60})})}>Adicionar resposta TXT</button>
 {preview&&<div aria-live="polite"><p>{preview.count} respostas encontradas. Primeiras 10:</p><pre className="variable-output">{preview.lines.join('\n')}</pre></div>}</Card>
 <Card title="Sons por espectador"><Toggle label="Ativar sons por espectador" checked={config.soundsEnabled} onChange={soundsEnabled=>setConfig({...config,soundsEnabled})}/><p className="help">A chegada é reconhecida pela primeira mensagem. Entrada silenciosa depende de uma ponte que envie join. Informe o nome exato do chat ou o ID da plataforma; o apelido serve para sua organização. Áudios são copiados para o BotLive, limitados a 5 MiB e reproduzidos por até 15 segundos. Capture o áudio do BotLive ou do desktop no OBS.</p>
 {config.people.map((r,i)=><section className="card" key={r.id}><div className="row between"><strong>{r.nickname||'Pessoa '+(i+1)}</strong><Toggle label={'Ativar som da pessoa '+(i+1)} checked={r.enabled} onChange={enabled=>person(r.id,{enabled})}/></div><div className="form-grid"><Field label="Nome no chat"><input value={r.name} maxLength={100} onChange={e=>person(r.id,{name:e.target.value})}/></Field><Field label="Apelido"><input value={r.nickname} maxLength={100} onChange={e=>person(r.id,{nickname:e.target.value})}/></Field></div><Field label="ID da pessoa (opcional)" hint="Quando preenchido, o ID tem prioridade sobre o nome; recomendado para evitar nomes duplicados."><input value={r.userId} maxLength={200} onChange={e=>person(r.id,{userId:e.target.value})}/></Field>
 {file('sound',r.asset,asset=>person(r.id,{asset}))}<div className="form-grid"><Field label="Quando tocar"><select value={r.mode} onChange={e=>person(r.id,{mode:e.target.value})}><option value="first">Primeira mensagem da sessão</option><option value="interval">Mensagens com intervalo</option></select></Field><Field label="Intervalo mínimo (segundos)"><input type="number" min="5" max="86400" value={r.cooldown} onChange={e=>person(r.id,{cooldown:+e.target.value})}/></Field></div><Field label={'Volume: '+Math.round(r.volume*100)+'%'}><input type="range" min="0" max="1" step="0.05" value={r.volume} onChange={e=>person(r.id,{volume:+e.target.value})}/></Field>
 <button disabled={!desktop||!r.asset} onClick={()=>void run(async()=>{await playViewerSound({profileId,asset:r.asset,volume:r.volume})})}>Testar som</button><button className="danger" onClick={()=>setConfig({...config,people:config.people.filter(x=>x.id!==r.id)})}>Remover pessoa</button></section>)}
 <button onClick={()=>setConfig({...config,people:config.people.concat({id:crypto.randomUUID(),enabled:true,name:'',nickname:'',userId:'',asset:'',mode:'first',cooldown:60,volume:0.7})})}>Adicionar pessoa</button><button disabled={!desktop} onClick={()=>void run(async()=>{await api('chatExtras.reset',{profileId});setMessage('Sessão de sons reiniciada. A próxima participação poderá tocar novamente.')})}>Reiniciar sessão de sons</button><p className="help">Há intervalo geral de 5 segundos entre sons. A sessão reinicia ao fechar o app ou pelo botão acima. Mantenha o aplicativo aberto e desbloqueado. Testar som reproduz mesmo com a função desativada.</p></Card>
 <footer className="form-footer"><button className="primary" disabled={!desktop} onClick={()=>void run(async()=>{await api('chatExtras.save',{profileId,config});setMessage('Respostas e sons salvos.')})}>Salvar respostas e sons</button></footer></fieldset>
 {error&&<p role="alert" className="inline-error">{error}</p>}{message&&<p role="status">{message}</p>}</div>
}
