import CommunityOptions from './CommunityOptions';
import {listen} from '@tauri-apps/api/event';
import {useEffect,useState} from 'react';
import ModuleSettings from './ModuleSettings';
import {Coins,Gift,Music,Users,Gamepad2,BarChart3,Volume2,Shield,MessageCircle,Mic,Plus,Play,SkipForward,ExternalLink} from 'lucide-react';
import {api,errorText,desktop} from './api';
import type {Profile,Community as Data} from './types';
import {Card,Field,Toggle,Tag,Modal,Empty} from './components';
const modules=[{id:'points',name:'Pontos & loja',description:'Reconheça quem participa do chat.',icon:Coins,color:'amber'},{id:'raffles',name:'Sorteios',description:'Uma palavra, uma chance de ganhar.',icon:Gift,color:'purple'},{id:'predictions',name:'Previsões',description:'Qual será o próximo resultado?',icon:BarChart3,color:'blue'},{id:'queue',name:'Fila para jogar',description:'Organize o próximo encontro.',icon:Users,color:'green'},{id:'songs',name:'Pedidos de música',description:'Sua comunidade escolhe o ritmo.',icon:Music,color:'pink'},{id:'games',name:'Jogos de chat',description:'Roleta, duelo e perguntas.',icon:Gamepad2,color:'purple'},{id:'tts',name:'Texto para voz',description:'Dê voz às mensagens da live.',icon:Volume2,color:'blue'},{id:'moderation',name:'Moderação',description:'Filtre links e mensagens repetidas.',icon:Shield,color:'amber'},{id:'discord',name:'Discord',description:'Leve momentos para o servidor.',icon:MessageCircle,color:'purple'},{id:'voice',name:'Controle por voz',description:'Receba comandos por ponte local.',icon:Mic,color:'green'}];
export default function Community({profile,onSaved,notify,onOpenResponses}:{profile:Profile;onSaved:()=>void;notify:(s:string)=>void;onOpenResponses:()=>void}){
 const [data,setData]=useState<Data|null>(null);const [active,setActive]=useState('points');const [dialog,setDialog]=useState('');const [form,setForm]=useState<Record<string,string>>({});const [hook,setHook]=useState('');
 const refresh=()=>api<Data>('community',{profileId:profile.id}).then(setData).catch(e=>notify(errorText(e)));
 useEffect(()=>{void refresh();if(!desktop)return;let disposed=false;let off:(()=>void)|undefined;void listen<{profileId:string}>('community',e=>{if(e.payload.profileId===profile.id)void refresh()}).then(f=>{if(disposed)f();else off=f});return()=>{disposed=true;off?.()}},[profile.id]);
 async function act(action:string,args:Record<string,unknown>={}){try{setData(await api<Data>('community.action',{profileId:profile.id,action,data:args}));setDialog('');notify('Comunidade atualizada.')}catch(e){notify(errorText(e))}}
 const field=(key:string,label:string,type='text')=><Field label={label}><input type={type} required value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field>;
 const names=(id:string)=>data?.names[id]||id;
 return <><div className="section-tools"><button onClick={onOpenResponses}>Respostas TXT e sons<ExternalLink size={15}/></button></div><div className="module-grid">{modules.map(m=><Card key={m.id} className={active===m.id?'module selected':'module'}><div className="module-top"><button aria-label={'Abrir '+m.name} className={'module-symbol '+m.color} onClick={()=>setActive(m.id)}><m.icon size={22}/></button><Toggle label={'Ativar '+m.name} checked={!!profile.modules?.[m.id]} onChange={async enabled=>{try{await api('profile.save',{profile:{...profile,modules:{...profile.modules,[m.id]:enabled}}});if(enabled&&m.id==='points')await act('shop_defaults');onSaved();notify(enabled?'Módulo ativado.':'Módulo desativado.')}catch(e){notify(errorText(e))}}}/></div><button className="module-title" onClick={()=>setActive(m.id)}>{m.name}</button><p>{m.description}</p></Card>)}</div><Card title={modules.find(m=>m.id===active)?.name} action={<Tag color={profile.modules?.[active]?'green':'amber'}>{profile.modules?.[active]?'Ativado':'Desativado'}</Tag>}>
 {active==='points'&&<><div className="section-tools"><p className="help">A pontuação por participação pode ser ajustada em Avançado. Use !pontos, !ranking, !transferir, !loja e !resgatar.</p><div className="row"><button onClick={()=>{setForm({});setDialog('points')}}>Ajustar saldo</button><button onClick={()=>{setForm({cost:'100',stock:'10'});setDialog('shop')}}><Plus size={15}/>Novo item</button></div></div><div className="two-columns"><div><h4>Loja de resgates</h4>{data?.shop.map((item,i)=><div className="list-row" key={item.id}><div><strong>{i+1}. {item.name}</strong><small>{item.stock} disponíveis</small></div><Tag color="amber">{item.cost} pontos</Tag></div>)}{!data?.shop.length&&<p className="help">Ative o módulo para criar três itens iniciais.</p>}</div><div><h4>Ranking da comunidade</h4>{Object.entries(data?.balances||{}).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([id,n],i)=><div className="list-row" key={id}><span><em>{i+1}</em> {names(id)}</span><strong>{n}</strong></div>)}{!Object.keys(data?.balances||{}).length&&<p className="help">Os pontos aparecem quando o chat participa.</p>}</div></div>{!!data?.redemptions.length&&<details><summary>Resgates recentes</summary>{data.redemptions.slice(-20).reverse().map((r,i)=><p key={i}>{r.user} · {r.item}</p>)}</details>}</>}
 {active==='raffles'&&<><p className="help">Entrada por palavra-chave ou !ticket quantidade. Bilhetes pagos usam os pontos do canal.</p><div className="stat-inline"><strong>{Object.keys(data?.raffle.entries||{}).length}</strong><span>participantes</span><strong>{Object.values(data?.raffle.entries||{}).reduce((a,b)=>a+b,0)}</strong><span>bilhetes</span></div>{data?.raffle.winner&&<div className="notice">Vencedor: <strong>{names(data.raffle.winner)}</strong></div>}<div className="row">{data?.raffle.open?<><Tag>{data.raffle.keyword}</Tag><button className="primary" onClick={()=>act('raffle_draw')}><Gift size={16}/>Sortear vencedor</button><button onClick={()=>act('raffle_cancel')}>Cancelar e reembolsar</button></>:<button className="primary" onClick={()=>{setForm({keyword:'!sorteio',price:'0'});setDialog('raffle')}}><Plus size={16}/>Abrir sorteio</button>}</div></>}
 {active==='predictions'&&<><p className="help">Aposte com !bet opção pontos. O total é dividido proporcionalmente entre os vencedores. Sem vencedores, todas as apostas são devolvidas.</p>{data?.prediction.open?<><h3>{data.prediction.title}</h3><div className="row wrap">{data.prediction.options.map((o,i)=><button key={i} onClick={()=>{setForm({result:String(i)});setDialog('settle')}}>Encerrar: {i+1}. {o}</button>)}</div><button onClick={()=>act('prediction_cancel')}>Cancelar e devolver pontos</button></>:<button className="primary" onClick={()=>{setForm({title:'Vamos vencer a próxima?',options:'Sim,Não'});setDialog('prediction')}}><Plus size={16}/>Nova previsão</button>}</>}
 {active==='queue'&&<><p className="help">Comandos: !entrar, !sair e !fila.</p>{data?.queue.map((u,i)=><div className="list-row" key={u}><span>{i+1}. {names(u)}</span><Tag>{i===0?'Próximo':'Na fila'}</Tag></div>)}{!data?.queue.length&&<p className="help">A fila está livre. Convide o chat para participar.</p>}<button disabled={!data?.queue.length} onClick={()=>act('queue_next')}><SkipForward size={16}/>Chamar próximo</button></>}
 {active==='songs'&&<><p className="help">!musica link · !minhamusica · !removermusica. Limites ajustáveis em Avançado. A reprodução ocorre no serviço original.</p>{data?.songs.map((s,i)=><div className="list-row" key={i}><div><strong>{names(s.user)}</strong><small>{s.url}</small></div><button onClick={()=>api('url.open',{url:s.url}).catch(e=>notify(errorText(e)))}><Play size={15}/>Abrir</button></div>)}{!data?.songs.length&&<p className="help">Nenhuma música pedida ainda.</p>}<button disabled={!data?.songs.length} onClick={()=>act('song_next')}><SkipForward size={15}/>Finalizar primeira música</button></>}
 {active==='games'&&<><p className="help">!roleta pontos (intervalo de 30 segundos), !duelo usuário pontos e !aceitar. Os jogos usam apenas os pontos virtuais deste canal.</p>{data?.trivia.open&&<div className="notice">Pergunta aberta: {data.trivia.question}</div>}<button className="primary" onClick={()=>{setForm({reward:'50'});setDialog('trivia')}}>Criar pergunta de trivia</button><button onClick={()=>act('bingo_open',{emotes:['Kappa','PogChamp','LUL','HeyGuys','SeemsGood','NotLikeThis','CoolCat','BibleThump','VoHiYo']})}>Abrir bingo de emotes</button><p className="help">No bingo, cada !bingo cria uma cartela de três emotes. Quem completar primeiro ganha 50 pontos.</p></>}
 {active==='tts'&&<ModuleSettings key={active} profileId={profile.id} kind={active} notify={notify}/>}
 {active==='moderation'&&<ModuleSettings key={active} profileId={profile.id} kind={active} notify={notify}/>}
 {active==='discord'&&<><p className="help">Salve o webhook do seu canal e use a ação “Enviar ao Discord” em um fluxo. Menções em massa são desativadas.</p><Field label="Webhook do Discord"><input type="password" autoComplete="new-password" value={hook} onChange={e=>setHook(e.target.value)} placeholder="https://discord.com/api/webhooks/…"/></Field><button onClick={async()=>{try{await api('secret.save',{profileId:profile.id,key:'discord_webhook',value:hook});setHook('');notify('Webhook salvo no cofre.')}catch(e){notify(errorText(e))}}}>Guardar webhook</button></>}
 {active==='voice'&&<ModuleSettings key={active} profileId={profile.id} kind={active} notify={notify}/>}
 {["points","songs","discord","games"].includes(active)&&<CommunityOptions key={active} profileId={profile.id} kind={active} notify={notify}/>}
 </Card>{dialog&&<Modal title={{points:'Ajustar pontos',shop:'Novo item na loja',raffle:'Abrir sorteio',prediction:'Nova previsão',settle:'Confirmar resultado',trivia:'Pergunta para a comunidade'}[dialog]||''} onClose={()=>setDialog('')}><form className="form-pad" onSubmit={e=>{e.preventDefault();if(dialog==='points')void act('points',{user:form.user,amount:Number(form.amount)});if(dialog==='shop')void act('shop_add',{name:form.name,cost:Number(form.cost),stock:Number(form.stock)});if(dialog==='raffle')void act('raffle_open',{keyword:form.keyword,price:Number(form.price)});if(dialog==='prediction')void act('prediction_open',{title:form.title,options:form.options.split(',').map(s=>s.trim()).filter(Boolean)});if(dialog==='settle')void act('prediction_settle',{result:Number(form.result)});if(dialog==='trivia')void act('trivia_open',{question:form.question,answer:form.answer,reward:Number(form.reward)})}}>
 {dialog==='points'&&<>{field('user','ID do espectador')}{field('amount','Pontos para adicionar ou remover','number')}</>}
 {dialog==='shop'&&<>{field('name','Nome do item')}{field('cost','Custo em pontos','number')}{field('stock','Quantidade disponível','number')}</>}
 {dialog==='raffle'&&<>{field('keyword','Palavra-chave')}{field('price','Custo de cada bilhete (0 = gratuito)','number')}</>}
 {dialog==='prediction'&&<>{field('title','Pergunta')}{field('options','Opções separadas por vírgula')}</>}
 {dialog==='settle'&&<p>Confirmar “{data?.prediction.options[Number(form.result)]}” como resultado? Os pontos serão distribuídos imediatamente.</p>}
 {dialog==='trivia'&&<>{field('question','Pergunta')}{field('answer','Resposta correta')}{field('reward','Recompensa em pontos','number')}</>}
 <footer className="form-footer"><button type="button" onClick={()=>setDialog('')}>Cancelar</button><button className="primary">Confirmar</button></footer></form></Modal>}</>
}
