import {useEffect,useState} from 'react';
import {Plus,Search,Trash2,Pencil,Play,Workflow,Save,Package} from 'lucide-react';
import {api,errorText} from './api';
import {newFlow,type Flow,type Profile,type Preset} from './types';
import {Card,Empty,Modal,Field,Toggle,Tag} from './components';
import FlowEditor from './FlowEditor';
import {VariableManager} from './Variables';
import MessageEditor from './MessageEditor';
import {ConversationForm} from './AIConversation';
export default function Commands({profile,visual,notify,onChanged,createToken}:{profile:Profile;visual:boolean;notify:(s:string)=>void;onChanged:()=>void;createToken:number}){
 const [variablesOpen,setVariablesOpen]=useState(false);const [conversationOpen,setConversationOpen]=useState(false);
 const [flows,setFlows]=useState<Flow[]>([]);const [query,setQuery]=useState('');const [editing,setEditing]=useState<Flow|null>(null);const [remove,setRemove]=useState<Flow|null>(null);const [simulate,setSimulate]=useState(false);const [message,setMessage]=useState('!oi');const [role,setRole]=useState('everyone');
 const refresh=()=>api<Flow[]>('flows',{profileId:profile.id}).then(setFlows).catch(e=>notify(errorText(e)));
 useEffect(()=>{void refresh()},[profile.id]);
 useEffect(()=>{if(createToken)setEditing(newFlow(profile.id))},[createToken]);
 async function save(flow:Flow){if(!flow.name.trim()||!flow.trigger.pattern&&flow.trigger.kind==='command')throw Error('Preencha o nome e o comando.');await api('flow.save',{flow});await refresh();onChanged();notify('Automação salva.');setEditing(null)}
 const visible=flows.filter(f=>(visual||f.trigger.kind==='command'||f.actions.some(a=>a.kind==='ai.generate'))&&(f.name+' '+f.trigger.pattern).toLowerCase().includes(query.toLowerCase()));
 return <><div className="section-tools"><div className="search"><Search size={17}/><input aria-label="Buscar comandos" value={query} onChange={e=>setQuery(e.target.value)} placeholder={visual?'Buscar automações…':'Buscar comandos…'}/></div><div className="row"><button onClick={()=>setConversationOpen(true)}>Resenha com IA</button><button onClick={()=>setVariablesOpen(true)}>Variáveis</button><button onClick={()=>setSimulate(true)}><Play size={15}/>Simular evento</button><button className="primary" onClick={()=>setEditing(newFlow(profile.id))}><Plus size={16}/>{visual?'Novo fluxo':'Novo comando'}</button></div></div>{visible.length?<Card><div className="table-scroll"><table><thead><tr><th>{visual?'Automação':'Comando'}</th><th>{visual?'Ações':'Resposta'}</th><th>Intervalo</th><th>Ativo</th><th></th></tr></thead><tbody>{visible.map(f=><tr key={f.id}><td><strong>{visual?f.name:f.trigger.pattern}</strong><small>{visual?f.trigger.pattern:f.name}</small></td><td className="response-cell">{visual?<Tag color="purple">{f.actions.length} ações conectadas</Tag>:f.actions[0]?.text}</td><td>{f.trigger.cooldown}s</td><td><Toggle checked={f.enabled} label={'Ativar '+f.name} onChange={async enabled=>{try{await api('flow.save',{flow:{...f,enabled}});await refresh();onChanged()}catch(e){notify(errorText(e))}}}/></td><td><div className="row"><button className="icon-button" aria-label={'Salvar preset '+f.name} onClick={async()=>{try{const preset=await api<Preset>('preset.create',{profileId:profile.id,kind:f.trigger.kind==='command'?'command':'flow',name:f.name,ids:[f.id]});await api('preset.save',{preset});notify('Salvo na biblioteca de presets.')}catch(e){notify(errorText(e))}}}><Package size={16}/></button><button className="icon-button" aria-label={'Editar '+f.name} onClick={()=>setEditing(f)}><Pencil size={16}/></button><button className="icon-button danger" aria-label={'Apagar '+f.name} onClick={()=>setRemove(f)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div></Card>:<Empty title={query?'Nenhum resultado':'Sua primeira conversa começa aqui'} action={<button className="primary" onClick={()=>setEditing(newFlow(profile.id))}><Plus size={16}/>Criar {visual?'fluxo':'comando'}</button>}>{query?'Tente outro nome ou comando.':'Crie uma resposta de boas-vindas, compartilhe suas redes ou deixe a IA participar do chat.'}</Empty>}{visual&&<div className="tip"><Workflow size={18}/><p>Uma ideia, várias ações. Conecte um gatilho a mensagens, IA, memória e overlays na ordem que você quiser.</p></div>}
 {conversationOpen&&<Modal title="Criar resenha com IA" onClose={()=>setConversationOpen(false)}><ConversationForm profileId={profile.id} onSave={async f=>{await save(f);setConversationOpen(false)}}/></Modal>}
 {variablesOpen&&<VariableManager profileId={profile.id} onClose={()=>setVariablesOpen(false)}/>}
 {editing&&<Modal wide={visual||editing.actions.length>1} title={visual?'Editor de automação':'Configurar comando'} onClose={()=>setEditing(null)}>{visual||editing.actions.length>1?<FlowEditor flow={editing} onSave={save}/>:<form className="form-pad" onSubmit={e=>{e.preventDefault();save(editing).catch(e=>notify(errorText(e)))}}><div className="form-grid"><Field label="Nome"><input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></Field><Field label="Comando"><input required pattern="![^\s]+" value={editing.trigger.pattern} onChange={e=>setEditing({...editing,trigger:{...editing.trigger,pattern:e.target.value}})}/></Field></div><MessageEditor profileId={profile.id} label="Resposta" required value={editing.actions[0].text} onChange={text=>setEditing({...editing,actions:[{...editing.actions[0],text}]})}/><div className="form-grid"><Field label="Quem pode usar"><select value={editing.trigger.permission} onChange={e=>setEditing({...editing,trigger:{...editing.trigger,permission:e.target.value}})}><option value="everyone">Todo mundo</option><option value="subscriber">Assinantes</option><option value="moderator">Moderadores</option><option value="broadcaster">Só o streamer</option></select></Field><Field label="Intervalo entre usos (segundos)"><input type="number" min="0" max="86400" value={editing.trigger.cooldown} onChange={e=>setEditing({...editing,trigger:{...editing.trigger,cooldown:+e.target.value}})}/></Field><Field label="Intervalo por pessoa (segundos)"><input type="number" min="0" max="86400" value={editing.trigger.userCooldown} onChange={e=>setEditing({...editing,trigger:{...editing.trigger,userCooldown:+e.target.value}})}/></Field></div><footer className="form-footer"><span className="help">Você pode evoluir este comando no editor visual.</span><button className="primary"><Save size={16}/>Salvar comando</button></footer></form>}</Modal>}
 {remove&&<Modal title="Apagar automação?" onClose={()=>setRemove(null)}><div className="form-pad"><p>“{remove.name}” será removida deste perfil.</p><footer className="form-footer"><button onClick={()=>setRemove(null)}>Cancelar</button><button className="danger" onClick={async()=>{try{await api('flow.delete',{profileId:profile.id,id:remove.id});setRemove(null);await refresh();onChanged()}catch(e){notify(errorText(e))}}}>Apagar</button></footer></div></Modal>}
 {simulate&&<Modal title="Simular evento de chat" onClose={()=>setSimulate(false)}><div className="form-pad"><p className="help">O teste não publica mensagens, não chama serviços e não altera memórias ou pontos. Acompanhe a sequência no histórico.</p><Field label="Mensagem"><input value={message} onChange={e=>setMessage(e.target.value)}/></Field><Field label="Permissão do espectador"><select value={role} onChange={e=>setRole(e.target.value)}><option value="everyone">Todo mundo</option><option value="subscriber">Assinante</option><option value="moderator">Moderador</option><option value="broadcaster">Streamer</option></select></Field><button className="primary" onClick={async()=>{try{await api('simulate',{event:{id:crypto.randomUUID(),profileId:profile.id,kind:'chat',user:'Espectador de teste',userId:'test-user',role,message,data:{},simulated:true}});notify('Simulação enviada. Veja o histórico.');setSimulate(false)}catch(e){notify(errorText(e))}}}><Play size={16}/>Executar simulação</button></div></Modal>}
 </>
}
