import {useEffect,useState,useRef} from 'react';
import {Mic,Square,Save,Volume2,Shield} from 'lucide-react';
import {api,errorText} from './api';
import {Field} from './components';
export default function ModuleSettings({profileId,kind,notify}:{profileId:string;kind:string;notify:(s:string)=>void}){
 const [config,setConfig]=useState<Record<string,unknown>>({});const [recording,setRecording]=useState(false);const [busy,setBusy]=useState(false);const stop=useRef<(()=>void)|null>(null);const cancelled=useRef(false);
 const [voices,setVoices]=useState<SpeechSynthesisVoice[]>([]);
 useEffect(()=>{api<Record<string,unknown>>('module.config.get',{profileId,key:kind}).then(v=>setConfig(v||{})).catch(e=>notify(errorText(e)));if(kind==='tts'){const load=()=>setVoices(speechSynthesis.getVoices());load();speechSynthesis.addEventListener('voiceschanged',load);return()=>speechSynthesis.removeEventListener('voiceschanged',load)}},[profileId,kind]);
 useEffect(()=>()=>{cancelled.current=true;stop.current?.()},[]);
 async function save(){await api('module.config',{profileId,key:kind,value:config})}
 async function record(){
 try{
 cancelled.current=false;await save();const stream=await navigator.mediaDevices.getUserMedia({audio:true});const ctx=new AudioContext();const source=ctx.createMediaStreamSource(stream);const processor=ctx.createScriptProcessor(4096,1,1);const chunks:Float32Array[]=[];processor.onaudioprocess=e=>chunks.push(new Float32Array(e.inputBuffer.getChannelData(0)));source.connect(processor);processor.connect(ctx.destination);setRecording(true);
 let finished=false;let timer:ReturnType<typeof setTimeout>;
 const end=async()=>{if(finished)return;finished=true;clearTimeout(timer);processor.disconnect();source.disconnect();stream.getTracks().forEach(t=>t.stop());const rate=ctx.sampleRate;await ctx.close();setRecording(false);stop.current=null;if(cancelled.current)return;
 const length=chunks.reduce((n,c)=>n+c.length,0);const pcm=new Float32Array(length);let offset=0;for(const chunk of chunks){pcm.set(chunk,offset);offset+=chunk.length}
 const count=Math.floor(length*16000/rate);const buffer=new ArrayBuffer(44+count*2);const view=new DataView(buffer);const text=(at:number,s:string)=>{for(let i=0;i<s.length;i++)view.setUint8(at+i,s.charCodeAt(i))};
 text(0,'RIFF');view.setUint32(4,36+count*2,true);text(8,'WAVE');text(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,16000,true);view.setUint32(28,32000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,count*2,true);
 for(let i=0;i<count;i++){const sample=Math.max(-1,Math.min(1,pcm[Math.floor(i*rate/16000)]));view.setInt16(44+i*2,sample<0?sample*32768:sample*32767,true)}
 let binary='';for(const b of new Uint8Array(buffer))binary+=String.fromCharCode(b);
 setBusy(true);try{const result=await api<{text:string}>('voice.transcribe',{profileId,audio:btoa(binary)});notify('Comando reconhecido: '+result.text)}catch(e){notify(errorText(e))}finally{setBusy(false)}
 };
 stop.current=()=>{void end()};timer=setTimeout(()=>void end(),8000);
 }catch(e){notify(errorText(e));setRecording(false)}
 }
 return <div className="module-settings">{kind==='moderation'&&<><p className="help">O bot ignora mensagens com expressões proibidas, links e repetições idênticas em 15 segundos. Streamer e moderadores ficam isentos.</p><Field label="O que fazer ao detectar?" hint="Avisos, timeout e banimento usam a conta do canal Twitch autorizada."><select value={String(config.action||'ignore')} onChange={e=>setConfig({...config,action:e.target.value})}><option value="ignore">Só ignorar e registrar</option><option value="warn">Enviar aviso nativo (Twitch)</option><option value="timeout">Aplicar timeout (Twitch)</option><option value="ban">Banir (Twitch)</option></select></Field>{config.action==='timeout'&&<Field label="Duração em segundos"><input type="number" min="1" max="1209600" value={Number(config.seconds)||60} onChange={e=>setConfig({...config,seconds:+e.target.value})}/></Field>}</>}{kind==='tts'&&<><p className="help">Adicione a ação “Ler em voz alta” ao fluxo. O texto passa pelo filtro do perfil antes da leitura.</p><Field label="Voz do sistema"><select value={String(config.voice||'')} onChange={e=>setConfig({...config,voice:e.target.value})}><option value="">Padrão em português</option>{voices.map(v=><option key={v.voiceURI} value={v.voiceURI}>{v.name} · {v.lang}</option>)}</select></Field><Field label="Velocidade"><input type="range" min=".5" max="2" step=".1" value={Number(config.rate)||1} onChange={e=>setConfig({...config,rate:+e.target.value})}/></Field><Field label="Limite de caracteres"><input type="number" min="1" max="500" value={Number(config.limit)||300} onChange={e=>setConfig({...config,limit:+e.target.value})}/></Field><button onClick={()=>{const u=new SpeechSynthesisUtterance('Olá, comunidade! O BotLive está pronto para a próxima live.');u.lang='pt-BR';u.rate=Number(config.rate)||1;u.voice=voices.find(v=>v.voiceURI===config.voice)||null;speechSynthesis.speak(u)}}><Volume2 size={15}/>Testar voz local</button></>}{kind==='voice'&&<><p className="help">Use um whisper-server local com endpoint /inference. Clique para gravar até 8 segundos. O áudio fica neste computador; a fala reconhecida dispara os fluxos “Comando de voz”.</p><Field label="Servidor local de reconhecimento"><input value={String(config.endpoint||'http://127.0.0.1:8080/inference')} onChange={e=>setConfig({...config,endpoint:e.target.value})}/></Field><button className="primary" disabled={busy} onClick={()=>recording?stop.current?.():void record()}>{recording?<Square size={15}/>:<Mic size={15}/>} {recording?'Parar e reconhecer':busy?'Reconhecendo…':'Gravar comando'}</button></>}<footer className="form-footer"><span className="help">Configuração exclusiva deste perfil</span><button onClick={()=>save().then(()=>notify('Configuração salva.')).catch(e=>notify(errorText(e)))}><Save size={15}/>Salvar configuração</button></footer></div>
}
