import UpdateSettings from './UpdateSettings';
import {version} from '../package.json';
import {applyAccent} from './appearance';
import {useEffect,useState} from 'react';
import {AccessSettings} from './Access';
import {Save,Copy,Monitor,Sun,Moon,ShieldCheck} from 'lucide-react';
import {api,errorText} from './api';
import {Card,Field,Toggle,Tag} from './components';
export default function Settings({theme,onTheme,notify,dataDir,onLock,profileId}:{profileId:string;theme:string;onTheme:(s:string)=>void;notify:(s:string)=>void;dataDir:string;onLock:()=>void}){
 const [settings,setSettings]=useState<Record<string,unknown>>({});const [show,setShow]=useState(false);const [loaded,setLoaded]=useState(false);
 useEffect(()=>{api<Record<string,unknown>>('settings.get').then(s=>{setSettings(s);setLoaded(true)}).catch(e=>notify(errorText(e)))},[]);
 async function persist(key:string,value:unknown){await api('settings',{key,value});setSettings(s=>({...s,[key]:value}));if(key==='accent')applyAccent(String(value))}
 return <div className="two-columns"><div><Card title="Do seu jeito"><Field label="Aparência"><div className="row"><button className={theme==='dark'?'selected':''} onClick={()=>onTheme('dark')}><Moon size={17}/>Escuro</button><button className={theme==='light'?'selected':''} onClick={()=>onTheme('light')}><Sun size={17}/>Claro</button></div></Field><Field label="Cor de destaque"><div className="row"><input aria-label="Cor de destaque" type="color" value={String(settings.accent||'#b7ef72')} onChange={e=>persist('accent',e.target.value).catch(e=>notify(errorText(e)))}/><button onClick={()=>persist('accent','').catch(e=>notify(errorText(e)))}>Restaurar padrão</button></div></Field>{profileId&&<button onClick={async()=>{try{const preset=await api('preset.create',{profileId,kind:'theme',name:'Meu tema'});await api('preset.save',{preset});notify('Tema salvo na biblioteca de presets.')}catch(e){notify(errorText(e))}}}>Salvar tema como preset</button>}<div className="list-row"><div><strong>Idioma</strong><small>Interface e orientação</small></div><Tag>Português · Brasil</Tag></div></Card><Card title="API local & overlays"><p className="help">Conecte Stream Deck e overlays à API WebSocket. Ela aceita conexões somente deste computador.</p><Field label="Porta local" hint="Reinicie o aplicativo depois de alterar."><input type="number" min="1024" max="65535" value={Number(settings.apiPort)||9876} onChange={e=>setSettings({...settings,apiPort:+e.target.value})}/></Field><button onClick={()=>persist('apiPort',settings.apiPort||9876).then(()=>notify('Porta salva. Reinicie para aplicar.')).catch(e=>notify(errorText(e)))}><Save size={15}/>Salvar porta</button><Field label="Chave de acesso da sessão" hint="Troca a cada abertura do app. Compartilhe só com integrações locais de confiança."><div className="row"><input readOnly type={show?'text':'password'} value={String(settings.apiToken||'')}/><button onClick={()=>setShow(!show)}>{show?'Ocultar':'Mostrar'}</button><button aria-label="Copiar chave da API" onClick={()=>navigator.clipboard.writeText(String(settings.apiToken||'')).then(()=>notify('Chave copiada.')).catch(()=>notify('Não foi possível copiar.'))}><Copy size={15}/></button></div></Field><p className="help">A primeira mensagem deve ser um JSON com o campo token. Consulte docs/API-LOCAL.md para o protocolo e o overlay de exemplo.</p></Card></div><div><UpdateSettings settings={settings} setSettings={setSettings} persist={persist} loaded={loaded}/><AccessSettings notify={notify} onLock={onLock}/><Card title="Seus dados ficam com você"><div className="tip compact"><ShieldCheck size={24}/><p>SQLite para configurações e histórico. Markdown para memórias. Cofre do sistema para credenciais.</p></div><Field label="Pasta de dados"><textarea readOnly rows={3} value={dataDir}/></Field><div className="list-row"><strong>BotLive</strong><Tag color="purple">{version}</Tag></div><small className="help"><Monitor size={13}/> Tauri 2 · Rust · React</small></Card></div></div>
}
