import {useEffect,useState,useRef} from 'react';
import {api,desktop,errorText} from './api';
import {Field,Modal} from './components';
import type {Flow} from './types';
import {variableCatalog,scopeNames,makeVariableToken,type VariableChoice} from './variableCatalog';

type Preview={text:string;steps:{kind:string;text:string}[];variables:Record<string,unknown>};
export function VariableHelp({profileId,text,onInsert,flow}:{profileId:string;text:string;onInsert:(value:string)=>void;flow?:Flow}){
 const [query,setQuery]=useState('');const [message,setMessage]=useState('!oi Ana 10');const [user,setUser]=useState('Ana');const [userId,setUserId]=useState('test-user');const [data,setData]=useState('{}');
 const [result,setResult]=useState<Preview|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const previewRequest=useRef(0);
 const [open,setOpen]=useState(false);const [group,setGroup]=useState('Todas');const [codes,setCodes]=useState(false);const [chosen,setChosen]=useState<VariableChoice|null>(null);const [fallback,setFallback]=useState('');const [format,setFormat]=useState('');const [saved,setSaved]=useState<VariableChoice[]>([]);const [loadError,setLoadError]=useState('');const [revision,setRevision]=useState(0);const [customScope,setCustomScope]=useState('local');const [customName,setCustomName]=useState('');
 useEffect(()=>{let active=true;setSaved([]);setLoadError('');if(open&&desktop)void api<Row[]>('variables.list',{profileId,userId}).then(rows=>{if(active)setSaved(rows.map(r=>({key:r.scope+'.'+r.name,label:r.name,group:'Minhas variáveis',example:scopeNames[r.scope]})))}).catch(e=>{if(active)setLoadError(errorText(e))});return()=>{active=false}},[open,profileId,userId,revision]);
 const available=new Map(variableCatalog.map(v=>[v.key,v]));for(const v of saved)available.set(v.key,v);
 for(const a of flow?.actions||[])if((a.kind==='variable.set'||a.kind==='variable.increment'||a.kind==='ai.generate')&&/^(local|global|user|session|sessionUser)\.[A-Za-z_][A-Za-z0-9_]*$/.test(a.target))available.set(a.target,{key:a.target,label:a.target.split('.').slice(1).join('.'),group:'Neste fluxo',example:'Disponível depois da ação que define o valor'});
 const choices=Array.from(available.values());const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const shown=choices.filter(v=>(group==='Todas'||group===v.group)&&normalize(v.key+' '+v.label).includes(normalize(query)));
 function choose(v:VariableChoice){setChosen(v);setFallback('');setFormat('');setError('')}
 function insert(){if(!chosen)return;try{onInsert(makeVariableToken(chosen.key,fallback,format));setError('');setChosen(null)}catch(e){setError(errorText(e))}}
 useEffect(()=>{previewRequest.current++;setResult(null);setError('');setBusy(false)},[profileId,text,message,user,userId,data,flow]);
 async function preview(){const request=++previewRequest.current;setBusy(true);setError('');setResult(null);try{const payload=JSON.parse(data);const next=await api<Preview>('variables.preview',{profileId,text:flow?'':text,flow,event:{id:'preview',profileId,kind:'chat',user,userId,role:'everyone',message,data:payload,simulated:true}});if(request===previewRequest.current)setResult(next)}catch(e){if(request===previewRequest.current)setError(errorText(e))}finally{if(request===previewRequest.current)setBusy(false)}}
 return <details className="variable-help" onToggle={e=>setOpen(e.currentTarget.open)}><summary>Inserir variável e testar mensagem</summary><p className="help">Escolha a informação pelo nome. Ela será inserida onde você deixou o cursor, substituindo o trecho selecionado.</p>
 <Field label="Buscar informação"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pessoa, canal, pedido, horário…"/></Field>
 <Field label="Categoria"><select value={group} onChange={e=>setGroup(e.target.value)}>{['Todas','Pessoa','Mensagem','Canal','Data e hora','Execução','IA','Minhas variáveis','Neste fluxo'].map(g=><option key={g}>{g}</option>)}</select></Field>
 <label className="variable-code-toggle"><input type="checkbox" checked={codes} onChange={e=>setCodes(e.target.checked)}/>Mostrar códigos técnicos</label>
 <div className="variable-catalog">{shown.map(v=><button type="button" key={v.key} onClick={()=>choose(v)}><strong>{v.label}</strong><small>{v.example?`${v.group} · ${v.example}`:v.group}</small>{codes&&<code>{'{{'+v.key+'}}'}</code>}</button>)}</div>
 {!shown.length&&<p className="help">Nenhuma informação nesta busca. Tente outra palavra ou categoria. As variáveis salvas são carregadas no desktop.</p>}
 {desktop&&<button type="button" onClick={()=>setRevision(v=>v+1)}>Atualizar minhas variáveis</button>}{loadError&&<p role="alert">{loadError}</p>}
 <details><summary>Usar uma variável personalizada</summary><p className="help">Escolha onde o valor está guardado e seu nome. O valor precisa existir antes de ser usado ou ter um texto alternativo.</p><Field label="Onde está o valor"><select value={customScope} onChange={e=>setCustomScope(e.target.value)}>{Object.entries(scopeNames).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></Field><Field label="Nome ou caminho do valor"><input value={customName} onChange={e=>setCustomName(e.target.value)} placeholder={customScope==='data'?'reward.title':'contador'}/></Field><button type="button" disabled={!customName} onClick={()=>choose({key:customScope+'.'+customName,label:customName,group:scopeNames[customScope]})}>Escolher este valor</button></details>
 {chosen&&<section className="variable-options" aria-label="Opções da informação"><h4>{chosen.label}</h4><Field label="Se não houver valor, mostrar" hint="Opcional. Por exemplo: amigo, nenhum ou 0."><input value={fallback} onChange={e=>setFallback(e.target.value)} placeholder="Manter sem alternativa"/></Field><Field label="Como mostrar"><select value={format} onChange={e=>setFormat(e.target.value)}><option value="">Como está</option><option value="upper">MAIÚSCULAS</option><option value="lower">minúsculas</option><option value="trim">Sem espaços nas pontas</option><option value="number:0">Número inteiro</option><option value="number:2">Número com duas casas</option><option value="length">Quantidade de caracteres ou itens</option></select></Field><div className="row"><button type="button" className="primary" onClick={insert}>Inserir na mensagem</button><button type="button" onClick={()=>setChosen(null)}>Cancelar escolha</button></div></section>}
 {error&&<p role="alert" className="inline-error">{error}</p>}
 <details className="variable-test"><summary>Testar como a mensagem vai ficar</summary>
 <h4>Conferir sem executar ações</h4><p className="help">{flow?'Calcula as ações de variável e os textos na ordem do fluxo.':'Resolve o conteúdo com os dados de teste.'} A prévia não envia mensagens nem grava variáveis. Scripts e serviços externos não são executados.</p>
 <Field label="Mensagem de teste"><input value={message} onChange={e=>setMessage(e.target.value)}/></Field>
 <Field label="Nome de teste"><input value={user} onChange={e=>setUser(e.target.value)}/></Field>
 <details><summary>Dados avançados do teste</summary><Field label="ID do usuário de teste"><input value={userId} onChange={e=>setUserId(e.target.value)}/></Field><Field label="Dados do evento (JSON)"><textarea rows={2} value={data} onChange={e=>setData(e.target.value)}/></Field></details>
 <button type="button" disabled={!desktop||busy} onClick={()=>void preview()}>{busy?'Calculando…':'Conferir variáveis'}</button>{!desktop&&<p className="help">Abra o aplicativo desktop para calcular a prévia com o motor real.</p>}
 {result&&<div aria-live="polite"><h4>Resultado</h4><pre className="variable-output">{flow?result.steps.map((s,i)=>`${i+1}. ${s.kind}: ${s.text}`).join('\n'):result.text}</pre><details><summary>Inspecionar valores disponíveis</summary><pre className="variable-output">{JSON.stringify(result.variables,null,2)}</pre></details></div>}</details>
 </details>
}
type Row={scope:string;name:string;value:unknown;userId:string};
export function VariableTarget({value,onChange}:{value:string;onChange:(v:string)=>void}){
 const dot=value.indexOf('.');const scope=dot<0?'local':value.slice(0,dot);const name=dot<0?value:value.slice(dot+1);
 return <div className="variable-target"><Field label="Guardar o valor"><select value={scope} onChange={e=>onChange(e.target.value+'.'+name)}>{Object.entries(scopeNames).filter(([key])=>key!=='data').map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></Field><Field label="Nome do valor" hint="Use letras sem acentos, números e sublinhado. Exemplo: contador."><input value={name} onChange={e=>onChange(scope+'.'+e.target.value)} placeholder="contador" maxLength={64}/></Field></div>
}
export function VariableManager({profileId,onClose}:{profileId:string;onClose:()=>void}){
 const [rows,setRows]=useState<Row[]>([]);const [userId,setUserId]=useState('');const [scope,setScope]=useState('global');const [name,setName]=useState('');const [value,setValue]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [valueType,setValueType]=useState('text');
 async function refresh(){if(!desktop)return;setBusy(true);try{setError('');setRows(await api<Row[]>('variables.list',{profileId,userId}))}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 useEffect(()=>{setRows([])},[userId]);useEffect(()=>{void refresh()},[profileId]);
 async function change(operation:string,target=scope+'.'+name){setBusy(true);setError('');try{let parsed:unknown=value;if(operation!=='delete'){if(valueType==='number'){if(!value.trim()||!Number.isFinite(Number(value)))throw Error('Informe um número válido, usando ponto nas casas decimais.');parsed=Number(value)}else if(valueType==='boolean')parsed=value==='true';else if(valueType==='json')parsed=JSON.parse(value)}await api('variables.change',{profileId,userId,target,operation,value:parsed});await refresh()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 function editRow(r:Row){setScope(r.scope);setName(r.name);setValueType(typeof r.value==='string'?'text':typeof r.value==='number'?'number':typeof r.value==='boolean'?'boolean':'json');setValue(typeof r.value==='string'?r.value:JSON.stringify(r.value))}
 return <Modal wide title="Variáveis do perfil" onClose={onClose}><div className="form-pad"><p>Organize textos, metas e contadores compartilhados entre comandos deste perfil. Globais e por usuário sobrevivem ao fechamento; variáveis de sessão são apagadas ao reiniciar.</p><p className="help">Não use este espaço para senhas ou tokens. Os valores ficam no banco local e podem aparecer nas respostas do bot.</p>
 <Field label="ID do usuário (para variáveis por pessoa)"><input disabled={busy} value={userId} onChange={e=>setUserId(e.target.value)} placeholder="ID da plataforma; não o nome exibido"/></Field><button type="button" disabled={!desktop||busy} onClick={()=>void refresh()}>Carregar variáveis</button>
 {!desktop&&<p className="help">O gerenciamento de variáveis está disponível no aplicativo desktop.</p>}
 <div className="form-grid"><Field label="Escopo"><select value={scope} onChange={e=>setScope(e.target.value)}><option value="global">Perfil · persistente</option><option value="user">Pessoa · persistente</option><option value="session">Perfil · sessão</option><option value="sessionUser">Pessoa · sessão</option></select></Field><Field label="Nome da variável"><input value={name} onChange={e=>setName(e.target.value)} placeholder="contador" maxLength={64}/></Field></div>
 <Field label="Tipo de valor"><select value={valueType} onChange={e=>{setValueType(e.target.value);if(e.target.value==='boolean')setValue('false')}}><option value="text">Texto</option><option value="number">Número / contador</option><option value="boolean">Sim ou não</option><option value="json">Lista ou objeto (JSON avançado)</option></select></Field><Field label="Valor">{valueType==='boolean'?<select value={value} onChange={e=>setValue(e.target.value)}><option value="true">Sim</option><option value="false">Não</option></select>:<textarea rows={3} value={value} onChange={e=>setValue(e.target.value)}/>}</Field><button type="button" className="primary" disabled={!desktop||busy||!name||(['user','sessionUser'].includes(scope)&&!userId)} onClick={()=>void change('set')}>Salvar variável</button>
 {error&&<p role="alert" className="inline-error">{error}</p>}
 <div className="table-scroll"><table><thead><tr><th>Variável</th><th>Valor</th><th>Ações</th></tr></thead><tbody>{rows.map(r=><tr key={r.scope+'.'+r.name}><td><strong>{r.name}</strong><small>{scopeNames[r.scope]}</small></td><td className="variable-cell">{typeof r.value==='string'?r.value:typeof r.value==='boolean'?(r.value?'Sim':'Não'):JSON.stringify(r.value)}</td><td><button type="button" disabled={busy} onClick={()=>editRow(r)}>Editar</button><button type="button" disabled={busy} className="danger" onClick={()=>{if(window.confirm('Apagar '+r.name+'?'))void change('delete',r.scope+'.'+r.name)}}>Apagar</button></td></tr>)}</tbody></table></div>{!rows.length&&<p className="help">Nenhuma variável carregada. Informe um ID e clique em carregar para incluir dados por pessoa.</p>}
 </div></Modal>
}
